services:
  postgres:
    image: postgres:16
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: test
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

  airportapi:
    image: mcr.microsoft.com/dotnet/sdk:8.0
    container_name: airportapi
    working_dir: /src
    volumes:
      - ./:/src
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=test;Username=postgres;Password=admin
    ports:
      - "5000:5000"
    command: tail -f /dev/null

volumes:
  postgres_data: